-- LEFT OUTER JOIN : 발표본 목차 상세조회 + 전략여부 및 페이지 추가 sql
SELECT A.PRSNTE_CNTNT_NO, A.CNTNT_NM, A.CNTNT_LVL, A.PAG, A.STGY_DTT_CD, B.CMN_CD_NM
FROM TB_PRSNTE_CONTNT A
LEFT OUTER JOIN (
	SELECT CMN_CD, CMN_CD_NM
	FROM TB_CMN_CD
	WHERE TP_CD = 'DCM_TP'
) B
ON A.STGY_DTT_CD = B.CMN_CD
WHERE PRPSL_NO = 9104
AND PRSNTE_CNTNT_NO != 0 AND CNTNT_NM IS NOT NULL;


-- INNER JOIN
SELECT 
    M.PRJ_CD, 
    M.PRJ_NM,
    TMP.PRJ_NM AS REPLACED_PRJ_NM,
    M.STD_YY, 
    M.BUSI_RPSR_NM, 
    M.PFRM_PM_NM, 
    M.LST_CUST, 
    M.BIZ_TP
FROM TB_PRPSL_MST M
INNER JOIN (
    SELECT PRPSL_NO, REPLACE(PRJ_NM , ' ', '') AS PRJ_NM
    FROM TB_PRPSL_MST
) TMP
ON M.PRPSL_NO = TMP.PRPSL_NO
WHERE TMP.PRJ_NM LIKE CONCAT('%', REPLACE('a o', ' ', ''), '%')
AND TMP.PRJ_NM LIKE CONCAT('%', REPLACE('2021', ' ', ''), '%');


-- 조인
SELECT * 
FROM TB_PRPSL_MST m, TB_PRSNTE_CONTNT p
WHERE m.PRPSL_NO = p.PRPSL_NO
AND m.PRJ_CD = 'AA.00.0000';