UPDATE TB_PRPSL_MST
SET PRPSL_INQ_CNT = 0;

UPDATE TB_PRPSL_MST
SET PRSNTE_INQ_CNT = 0;

-- 제안서 조회수 카운트
UPDATE TB_PRPSL_MST
SET PRPSL_INQ_CNT = PRPSL_INQ_CNT + 1
WHERE PRPSL_NO = 8884;

-- 발표본 조회수 카운트
UPDATE TB_PRPSL_MST
SET PRSNTE_INQ_CNT = PRSNTE_INQ_CNT + 1
WHERE PRPSL_NO = 8884;

-- 다운로드 수 카운트
UPDATE TB_PRPSL_FL
SET DNL_CNT = DNL_CNT + 1
WHERE PRPSL_NO = 9235
AND PRPSL_FL_NO = 1;


물리경로: 루트부터 시작
논리경로:

절대경로: 루트부터 시작
상대경로: 